### ISSUE TITLE
Fix Tutorial 14

### ISSUE THREAD

**Issue by ndaelman-hu** [FAIRmat-NFDI/nomad-parser-vasp#8]
Installing tutorial 14 fresh, I get the following error when running `nomad parse --show-archive tests/vasprun.xml.relax`:

```python
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/MDAnalysis/topology/TPRParser.py:161: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
  import xdrlib
Schema is deprecated, use plugins. ()
SOAP normalizer runs, but quippy is not installed. (normalizer=SoapNormalizer)
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['hall_number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['hall']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['pointgroup']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['wyckoffs']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_lattice']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_positions']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_types']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['mapping_to_primitive']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_mapping_to_primitive']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['crystallographic_orbits']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['transformation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['origin_shift']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
Unexpected error during normalizing (normalizer=SystemNormalizer, section=system, g_index=2, exc_info=cannot import name 'StringIO' from 'msgpack.fallback' (/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/msgpack/fallback.py), error=cannot import name 'StringIO' from 'msgpack.fallback' (/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/msgpack/fallback.py))
Traceback (most recent call last):
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/cli/cli.py", line 76, in run_cli
    return cli(obj=POPO())  # pylint: disable=E1120,E1123
           ^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/cli/parse.py", line 87, in _parse
    normalize_all(entry_archive)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/client/processing.py", line 111, in normalize_all
    normalize(normalizer, entry_archive, logger=logger)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/client/processing.py", line 96, in normalize
    normalizer_instance.normalize(logger=logger)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/normalizing/__init__.py", line 79, in normalize
    self.normalizer.normalize(self.archive, logger)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/normalizing/normalizer.py", line 194, in normalize
    self.__normalize_system(archive, repr_sys, True, logger)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/normalizing/normalizer.py", line 177, in __normalize_system
    raise e
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/normalizing/normalizer.py", line 155, in __normalize_system
    return self._normalize_system(archive, system, representative)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/normalizing/normalizer.py", line 78, in _normalize_system
    return self.normalize_system(archive, system, is_representative)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/systemnormalizer/normalizer.py", line 296, in normalize_system
    self.symmetry_analysis(section_run, system, atoms)
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/systemnormalizer/normalizer.py", line 445, in symmetry_analysis
    self.springer_classification(section_run, atoms, space_group_number)  # Springer Normalizer
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/systemnormalizer/normalizer.py", line 450, in springer_classification
    springer_data = query_springer_data(normalized_formula, space_group_number)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/systemnormalizer/normalizer.py", line 543, in query_springer_data
    from nomad import archive
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/archive/__init__.py", line 36, in <module>
    from .storage import (
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/archive/storage.py", line 25, in <module>
    from msgpack.fallback import Packer, StringIO
ImportError: cannot import name 'StringIO' from 'msgpack.fallback' (/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/msgpack/fallback.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/bin/nomad", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/nathan/Documents/nomad-parser-vasp/.pyenv/lib/python3.11/site-packages/nomad/cli/cli.py", line 80, in run_cli
    if next(arg for arg in sys.argv if arg == '-v') is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by ndaelman-hu** [comment]
@Bernadette-Mohr got

```python
Schema is deprecated, use plugins. ()
Length of `AtomicCell.positions` does not coincide with the length of the `AtomicCell.atoms_state`. (normalizer=MetainfoNormalizer)
Could not extract the geometric space information from ASE Atoms object. (normalizer=MetainfoNormalizer)
could not normalize section (normalizer=MetainfoNormalizer, section=DFT, exc_info=max() arg is an empty sequence)
```

**Comment by ndaelman-hu** [comment]
Any fix should also decide on how to handle `add_run`: merge it into `tutorial-14` or delete the branch

**Comment by JosePizarro3** [comment]
Weird. The spglib deprecation warning is ok. The other error is related with the `SystemNormalizer`, which should not affect `data`...

@Bernadette-Mohr error is more understandable and depends on the testing case and the population of the relevant classes.
